language: node_js

cache: yarn

script:
  - yarn lint
  - yarn test

notifications:
  email: false
  slack: interfirm:L2WhP1umnVtkeYcz6Uedkocs#developer

deploy:
  provider: npm
  email: register@interfirm.co.jp
  api_key:
    secure: bUvVKDSKQe3UmYFZLQfVfv8GceRFnfKIse1ni56TXSFfeI1LcjXDF/nf5OEWW4P5jRBNHLgSfdh9BNwh2UOtwyuGBCennzfbTF50wFiAirT8EcNhkvS2IPf34uu+xUQkqsyjym4q0434MtLdAB0xqpPDVJ7xI8NkU9VdBs02uJpxDfU1idGQG6up9Qk9Ew5LWZf532Qpl6H2TH3TCgPK7XIU7+CLg+ljNyZjgBElxbab+BAxkoWfASNNLgbbbh0+sBKI/O0ZUYHB3F9YCgkuVRSY/F77ht+LiYe7uJQ/uJavTEOoxztBnrERhacXi6T7YvGuOXQQWGci7xAUjBM3Q9BUVRm400qNiEPdMTkL3zV3lJjOSGDRx2Q513Nx90mAaR0oLw0ogpsHFiFFwaxDRK/xfnkKWS9UeUN6dang1MFyWaIiC7XH4EB6yQejn4DyfVVMTAXxuOVSsrKwVYj3lbTVxQS08eUfISnHIGoIzKFHhlF50YiMRxXtZAv1dbg/TN6NWmMNdgY0VVyjLr5VLQgriolZT7XGdRNgbPiCTUAZsxLFDbVcyxrItB8Dxk8Ivul9xq7h4xM8YgEkXr3xl3xgSrbCTj0zT3BK4qniDEWUdIYEB/5760RGk3eFLoL39LE90DBoctJdyuw7Oxr4C7eXllmFQUVbmgGVuyv2mgQ=
  on:
    tags: true
  skip_cleanup: true
