version: '2.1'

workflows:
  test:
    jobs:
      - test

jobs:
  test:
    executor: node
    steps:
      - checkout
      - yarn_install
      - run: yarn lint
      - run: yarn test

executors:
  node:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/repo

commands:
  yarn_install:
    steps:
      - run: yarn --version
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

