---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  reek:
    enabled: true
  markdownlint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
exclude_paths:
- config/**/*
- db/**/*
- vendor/**/*
- spec/**/*
- test/**/*
- frontend/javascripts/components/**/*
