version: "2"
checks:
  argument-count:
    enabled: false
  file-lines:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  return-statements:
    enabled: false
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  reek:
    enabled: true
  markdownlint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 30
  fixme:
    enabled: true
exclude_patterns:
- config/**/*
- db/**/*
- vendor/**/*
- spec/**/*
- test/**/*
- frontend/javascripts/components/**/*
