version: "2"
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  reek:
    enabled: true
  markdownlint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
exclude_patterns:
- config/**/*
- db/**/*
- vendor/**/*
- spec/**/*
- test/**/*
- frontend/javascripts/components/**/*
