AllCops:
  TargetRailsVersion: 5.1
  Exclude:
    - "db/schema.rb"
    - "log/**/*"
    - "public/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    - !ruby/regexp /config\/(?!routes\.rb$).*/
  UseCache: true
  DisplayCopNames: true
  DisplayStyleGuide: true

Rails:
  Enabled: true

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - production
    - staging

# Top-level class documentation comment is unnecessary in most cases
Style/Documentation:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

# Allow Japanese comments.
Style/AsciiComments:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Layout/DotPosition:
  Enabled: true
  EnforcedStyle: trailing

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Enabled: true
  Max: 100

Metrics/ClassLength:
  Enabled: true
  Max: 100
  Exclude:
    - "test/**/*"
    - "spec/**/*"

Metrics/MethodLength:
  Enabled: true
  CountComments: false
  Max: 20
  Exclude:
    - "test/**/*"
    - "spec/**/*"

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - "test/**/*"
    - "spec/**/*"
    - "**/*.jbuilder"

Metrics/AbcSize:
  Enabled: true
  Max: 25
  Exclude:
    - "test/**/*"
    - "spec/**/*"
